import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { CookieConsent } from '@/components/cookie-consent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-col min-h-[100vh] ">
      <Header />
      <main className="flex-1 ">{children}</main>
      <Footer />
      <CookieConsent />
    </main>
  );
}
